import { useState, useCallback } from 'react';
import { ChevronRight, ChevronDown, FileText } from 'lucide-react';
import type { HeraldReport, CasualtyDisposition } from '@/lib/herald-types';
import { PRIORITY_COLORS, DISPOSITION_LABELS, SERVICE_LABELS } from '@/lib/herald-types';
import type { HeraldSession } from '@/lib/herald-session';
import { sanitizeAssessment, formatActionAge } from '@/lib/sanitize-assessment';
import type { ActionItem, Assessment } from '@/lib/herald-types';
import { getReports } from '@/lib/herald-storage';

interface ReportsTabProps {
  closedCasualties: CasualtyDisposition[];
  reports: HeraldReport[];
  session?: HeraldSession;
}

function CopyBtn({ text, label }: { text: string; label: string }) {
  const [copied, setCopied] = useState(false);
  const copy = useCallback(() => {
    navigator.clipboard.writeText(text);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  }, [text]);
  return (
    <button onClick={copy}
      className="text-lg text-foreground border border-border px-3 py-1.5 rounded-sm bg-transparent cursor-pointer tracking-wide hover:border-primary transition-colors">
      {copied ? 'COPIED' : label}
    </button>
  );
}

function getTime(ts: string | null) {
  if (!ts) return '';
  const d = new Date(ts);
  return d.getUTCHours().toString().padStart(2, '0') + ':' +
    d.getUTCMinutes().toString().padStart(2, '0') + 'Z';
}

/** Build ePRF for a closed casualty */
function buildClosedEprf(d: CasualtyDisposition, report: HeraldReport): string {
  const a = report.assessment ? sanitizeAssessment(report.assessment as unknown as Assessment) : null;
  const ts = new Date(report.timestamp);
  const dateStr = ts.toISOString().slice(0, 10);
  const timeStr = ts.getUTCHours().toString().padStart(2, '0') + ':' +
    ts.getUTCMinutes().toString().padStart(2, '0') + ':' +
    ts.getUTCSeconds().toString().padStart(2, '0') + 'Z';
  const incidentNum = report.incident_number ?? (a?.structured as any)?.incident_number ?? '—';

  // Extract casualty ATMIST
  const atmistData = a?.atmist ? (a.atmist as any)[d.casualty_key] : null;
  const atmistLines = atmistData ? [
    `  Age/Sex: ${atmistData.A ?? '—'}`,
    `  Time of Injury: ${atmistData.T ?? '—'}`,
    `  Mechanism: ${atmistData.M ?? '—'}`,
    `  Injuries: ${atmistData.I ?? '—'}`,
    `  Signs/Vitals: ${atmistData.S ?? '—'}`,
    `  Treatment: ${atmistData.T_treatment ?? '—'}`,
  ].join('\n') : '  No ATMIST data';

  const dispLabel = DISPOSITION_LABELS[d.disposition];
  const hospitalLine = d.disposition === 'conveyed'
    ? `RECEIVING HOSPITAL: ${(report as any).receiving_hospital || (a?.receiving_hospital as string[])?.join(', ') || 'Not specified'}`
    : '';

  return `ePRF — PATIENT HANDOVER
═══════════════════════════
INCIDENT: ${incidentNum}
DATE/TIME: ${dateStr} ${timeStr}
CALLSIGN: ${report.session_callsign ?? '—'}

PATIENT: ${d.casualty_label}
PRIORITY: ${d.priority}

ATMIST:
${atmistLines}

DISPOSITION: ${dispLabel}${d.refer_to ? ` — ${d.refer_to}` : ''}${d.capacity_assessed ? ' (Capacity assessed)' : ''}
${hospitalLine}
HANDED OVER: ${new Date(d.closed_at).toISOString().slice(0, 16).replace('T', ' ')}Z
═══════════════════════════
Generated by Herald Radio Intelligence`;
}

export function ReportsTab({ closedCasualties, reports, session }: ReportsTabProps) {
  const [expandedKey, setExpandedKey] = useState<string | null>(null);
  const [eprfKey, setEprfKey] = useState<string | null>(null);

  if (closedCasualties.length === 0 && session) {
    return (
      <div className="flex-1 flex flex-col items-center justify-center px-4">
        <span className="text-lg uppercase font-bold mb-4" style={{ color: '#4A6058' }}>
          {SERVICE_LABELS[session.service] ?? session.service}
        </span>
        <p style={{ color: '#1E3028', fontSize: 18, letterSpacing: '0.2em', marginBottom: 8 }}>
          NO HANDED OVER PATIENTS THIS SHIFT
        </p>
        <p style={{ color: '#1E3028', fontSize: 18 }}>
          {session.callsign} · {session.session_date}
        </p>
      </div>
    );
  }

  return (
    <div className="flex-1 overflow-auto px-3 py-3">
      <p className="text-lg text-foreground tracking-[0.1em] mb-3 font-bold">
        HANDED OVER ({closedCasualties.length})
      </p>

      {closedCasualties.map((d) => {
        const uniqueKey = `${d.incident_id}-${d.casualty_key}`;
        const report = reports.find(r => r.id === d.incident_id) ?? getReports().find(r => r.id === d.incident_id);
        if (!report) return null;

        const a = report.assessment ? sanitizeAssessment(report.assessment as unknown as Assessment) : null;
        const col = PRIORITY_COLORS[d.priority] ?? '#34C759';
        const expanded = expandedKey === uniqueKey;
        const showEprf = eprfKey === uniqueKey;
        const dispLabel = DISPOSITION_LABELS[d.disposition];

        // Extract ATMIST for this casualty
        const atmistData = a?.atmist ? (a.atmist as any)[d.casualty_key] : null;

        return (
          <div key={uniqueKey} className="mb-3 rounded-lg border border-border bg-card shadow-sm overflow-hidden">
            <button
              onClick={() => setExpandedKey(expanded ? null : uniqueKey)}
              className="w-full text-left p-3">
              <div className="flex items-center gap-3">
                {expanded
                  ? <ChevronDown size={18} className="text-foreground opacity-50 flex-shrink-0" />
                  : <ChevronRight size={18} className="text-foreground opacity-50 flex-shrink-0" />}
                <span className="text-lg font-bold rounded-sm px-2 py-0.5 flex-shrink-0"
                  style={{ color: col, border: `1px solid ${col}66`, background: `${col}1A` }}>
                  {d.priority}
                </span>
                <div className="flex-1 min-w-0">
                  <p className="text-lg text-foreground font-medium truncate">
                    {d.casualty_label.replace(/^P\d\s*—\s*/, '') || 'Patient'}
                  </p>
                  <p className="text-lg text-foreground opacity-60">
                    {dispLabel} · {getTime(d.closed_at)}
                  </p>
                </div>
              </div>
            </button>

            {expanded && (
              <div className="px-3 pb-4 border-t border-border">
                {/* Disposition */}
                <div className="mt-3 rounded-lg p-3" style={{ background: `${col}1A`, borderLeft: `4px solid ${col}` }}>
                  <p className="text-lg font-bold" style={{ color: col }}>{d.priority} — {dispLabel}</p>
                  {d.refer_to && (
                    <p className="text-lg text-foreground mt-1">Referred to: {d.refer_to}</p>
                  )}
                  {d.capacity_assessed && (
                    <p className="text-lg mt-1" style={{ color: '#34C759' }}>✓ Capacity assessment completed</p>
                  )}
                  <p className="text-lg text-foreground opacity-60 mt-1">
                    Handed over {getTime(d.closed_at)}
                    {d.incident_number ? ` · Incident #${d.incident_number}` : ''}
                  </p>
                </div>

                {/* ATMIST */}
                {atmistData && (
                  <div className="mt-4">
                    <p className="text-lg font-bold tracking-[0.2em] mb-2" style={{ color: '#1E90FF' }}>ATMIST</p>
                    <div className="border border-border rounded-lg bg-card p-3">
                      {[
                        { k: 'A', label: 'Age / Sex' },
                        { k: 'T', label: 'Time of Injury' },
                        { k: 'M', label: 'Mechanism' },
                        { k: 'I', label: 'Injuries' },
                        { k: 'S', label: 'Signs / Vitals' },
                        { k: 'T_treatment', label: 'Treatment Given' },
                      ].map(({ k, label }) => (
                        <div key={k} className="mb-2 last:mb-0">
                          <span className="text-lg font-bold" style={{ color: '#1E90FF' }}>{label}: </span>
                          <span className="text-lg text-foreground break-words">{atmistData[k] ?? '—'}</span>
                        </div>
                      ))}
                    </div>
                  </div>
                )}

                {/* Receiving hospital for conveyed */}
                {d.disposition === 'conveyed' && (
                  <div className="mt-4">
                    <p className="text-lg font-bold tracking-[0.2em] mb-2" style={{ color: col }}>RECEIVING HOSPITAL</p>
                    <div className="border border-border rounded-lg p-3">
                      <p className="text-xl text-foreground font-bold break-words">
                        {(report as any).receiving_hospital || (a?.receiving_hospital as string[])?.join(', ') || 'Not specified'}
                      </p>
                    </div>
                  </div>
                )}

                {/* ePRF */}
                <div className="mt-4">
                  <button
                    onClick={() => setEprfKey(showEprf ? null : uniqueKey)}
                    className="w-full flex items-center justify-center gap-2 py-3 rounded-lg text-lg font-bold tracking-[0.15em] border cursor-pointer transition-colors"
                    style={{
                      color: showEprf ? '#1A1E24' : 'hsl(var(--primary))',
                      background: showEprf ? 'hsl(var(--primary))' : 'transparent',
                      borderColor: 'hsl(var(--primary))',
                    }}>
                    <FileText size={20} />
                    {showEprf ? 'HIDE ePRF' : 'VIEW ePRF'}
                  </button>
                  {showEprf && (
                    <div className="mt-3">
                      <div className="flex items-center justify-between mb-2">
                        <p className="text-lg font-bold tracking-[0.2em]" style={{ color: 'hsl(var(--primary))' }}>
                          ePRF — PATIENT HANDOVER
                        </p>
                        <CopyBtn text={buildClosedEprf(d, report)} label="COPY ePRF" />
                      </div>
                      <div className="border border-border rounded-lg bg-card p-3">
                        <div className="text-lg text-foreground leading-7 whitespace-pre-wrap break-words">
                          {buildClosedEprf(d, report)}
                        </div>
                      </div>
                    </div>
                  )}
                </div>
              </div>
            )}
          </div>
        );
      })}
    </div>
  );
}
