import { useState, useCallback } from 'react';
import type { CommandReport } from '@/hooks/useHeraldCommand';
import { SERVICE_EMOJIS, PRIORITY_COLORS } from '@/lib/herald-types';

interface Props {
  report: CommandReport | null;
}

function CopyBtn({ text, label }: { text: string; label: string }) {
  const [copied, setCopied] = useState(false);
  const copy = useCallback(() => {
    navigator.clipboard.writeText(text);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  }, [text]);

  return (
    <button
      onClick={copy}
      style={{
        fontSize: 18,
        color: '#FFFFFF',
        border: '1px solid #0F1820',
        padding: '6px 14px',
        borderRadius: 2,
        background: 'transparent',
        cursor: 'pointer',
        letterSpacing: '0.05em',
      }}
    >
      {copied ? 'COPIED' : label}
    </button>
  );
}

function SectionLabel({ children, color }: { children: React.ReactNode; color?: string }) {
  return (
    <div style={{ fontSize: 18, fontWeight: 700, color: color ?? '#FFFFFF', letterSpacing: '0.2em', marginBottom: 10 }}>
      {children}
    </div>
  );
}

function Card({ children }: { children: React.ReactNode }) {
  return (
    <div style={{ border: '1px solid #0F1820', borderRadius: 4, padding: '16px 18px', background: '#0D1117' }}>
      {children}
    </div>
  );
}

export function ReportDetail({ report }: Props) {
  if (!report) {
    return (
      <div className="flex flex-col items-center justify-center h-full">
        <span className="font-heading" style={{ fontSize: 48, color: '#0D1117' }}>
          HERALD COMMAND
        </span>
        <span style={{ fontSize: 18, color: '#FFFFFF', letterSpacing: '0.2em', marginTop: 8 }}>
          SELECT A TRANSMISSION
        </span>
      </div>
    );
  }

  const a = report.assessment;
  const priority = a?.priority ?? report.priority ?? 'P3';
  const col = PRIORITY_COLORS[priority] ?? '#34C759';
  const service = a?.service ?? report.service ?? 'unknown';
  const emoji = SERVICE_EMOJIS[service] ?? '📻';
  const ts = new Date(report.created_at ?? report.timestamp);
  const timeStr = ts.getUTCHours().toString().padStart(2, '0') + ':' +
    ts.getUTCMinutes().toString().padStart(2, '0') + ':' +
    ts.getUTCSeconds().toString().padStart(2, '0') + 'Z';
  const dateStr = ts.toISOString().slice(0, 10);

  const structured = a?.structured ?? {};
  const actions = a?.actions ?? [];
  const formattedReport = a?.formatted_report ?? '';
  const headline = a?.headline ?? report.headline ?? '';
  const confidence = a?.confidence ?? 0;
  const transmitTo = a?.transmit_to ?? '';
  const protocol = a?.protocol ?? '';
  const priorityLabel = a?.priority_label ?? '';

  // ePRF mapping
  const location = structured['E'] ?? structured['Location'] ?? structured['grid'] ?? 'Not specified';
  const clinicalFindings = Object.entries(structured).map(([k, v]) => `${k}: ${v}`).join('. ');
  const treatmentGiven = actions.join('. ');
  const eprfText = `INCIDENT DATE/TIME: ${dateStr} ${timeStr}
INCIDENT TYPE: ${protocol}
LOCATION: ${location}
CHIEF COMPLAINT: ${headline}
HISTORY: ${report.transcript ?? 'N/A'}
CLINICAL FINDINGS: ${clinicalFindings}
TREATMENT GIVEN: ${treatmentGiven}
PRIORITY: ${priorityLabel}
CREW NOTES: Generated by Herald Radio Intelligence`;

  return (
    <div className="h-full overflow-y-auto p-4 flex flex-col gap-5" style={{ scrollbarWidth: 'thin' }}>
      {/* Priority Banner */}
      <div
        style={{
          background: `${col}1F`,
          borderBottom: `3px solid ${col}`,
          borderRadius: 4,
          padding: '18px 20px',
        }}
      >
        <div className="flex items-center justify-between">
          <div className="flex items-center gap-4">
            <span style={{ fontSize: 40 }}>{emoji}</span>
            <div className="flex items-baseline gap-3">
              <span className="font-heading" style={{ fontSize: 48, color: col, lineHeight: 1 }}>
                {priority}
              </span>
              <span className="font-heading" style={{ fontSize: 28, color: col, letterSpacing: '0.05em' }}>
                {priorityLabel}
              </span>
            </div>
          </div>
          <div className="text-right">
            <div style={{ fontSize: 20, color: '#FFFFFF', textTransform: 'uppercase', fontWeight: 700 }}>{service}</div>
            <div style={{ fontSize: 18, color: '#FFFFFF', marginTop: 4 }}>{dateStr} {timeStr}</div>
          </div>
        </div>
      </div>

      {/* Headline */}
      <Card>
        <p style={{ fontSize: 20, color: '#FFFFFF', lineHeight: 1.6, fontWeight: 500 }}>{headline}</p>
      </Card>

      {/* Full Transcript */}
      <div>
        <SectionLabel>FULL TRANSCRIPT</SectionLabel>
        <Card>
          <p style={{ fontSize: 18, color: '#FFFFFF', lineHeight: 1.7, fontStyle: 'italic' }}>
            &ldquo;{report.transcript ?? 'N/A'}&rdquo;
          </p>
          <div style={{ fontSize: 18, color: '#FFFFFF', marginTop: 10, opacity: 0.7 }}>
            CONFIDENCE: {Math.round(confidence * 100)}%
          </div>
        </Card>
      </div>

      {/* Two col grid */}
      <div className="grid grid-cols-1 md:grid-cols-2 gap-5">
        {/* Protocol Fields */}
        <div>
          <SectionLabel color={col}>PROTOCOL FIELDS</SectionLabel>
          <Card>
            <div className="flex flex-col gap-3">
              {Object.entries(structured).map(([k, v]) => (
                <div key={k}>
                  <div style={{ fontSize: 18, fontWeight: 700, color: col, letterSpacing: '0.05em', marginBottom: 2 }}>{k}</div>
                  <div style={{ fontSize: 18, color: '#FFFFFF', lineHeight: 1.5 }}>{v ?? '—'}</div>
                </div>
              ))}
              {Object.keys(structured).length === 0 && (
                <span style={{ fontSize: 18, color: '#FFFFFF', opacity: 0.5 }}>No structured fields</span>
              )}
            </div>
          </Card>
        </div>

        {/* Actions */}
        <div>
          <SectionLabel color={col}>IMMEDIATE ACTIONS</SectionLabel>
          <Card>
            <div className="flex flex-col gap-2">
              {actions.map((act, i) => (
                <div key={i} className="flex gap-3">
                  <span style={{ fontSize: 18, fontWeight: 700, color: col, minWidth: 24 }}>{i + 1}.</span>
                  <span style={{ fontSize: 18, color: '#FFFFFF', lineHeight: 1.5 }}>{act}</span>
                </div>
              ))}
            </div>
            {transmitTo && (
              <>
                <div style={{ borderTop: '1px solid #0F1820', margin: '14px 0' }} />
                <div style={{ fontSize: 18, color: '#FFFFFF' }}>
                  <span style={{ fontWeight: 700, color: col }}>TRANSMIT TO:</span> {transmitTo}
                </div>
              </>
            )}
          </Card>
        </div>
      </div>

      {/* Formatted Report */}
      <div>
        <div className="flex items-center justify-between mb-2">
          <SectionLabel>FORMATTED REPORT</SectionLabel>
          <CopyBtn text={formattedReport} label="COPY" />
        </div>
        <Card>
          <pre style={{ fontSize: 18, color: '#FFFFFF', lineHeight: 1.8, whiteSpace: 'pre-wrap' }}>
            {formattedReport || 'No formatted report available'}
          </pre>
        </Card>
      </div>

      {/* ePRF Export */}
      <div>
        <div className="flex items-center justify-between mb-2">
          <SectionLabel color="#3DFF8C">ePRF READY</SectionLabel>
          <CopyBtn text={eprfText} label="COPY ePRF" />
        </div>
        <Card>
          <pre style={{ fontSize: 18, color: '#FFFFFF', lineHeight: 1.7, whiteSpace: 'pre-wrap' }}>
            {eprfText}
          </pre>
        </Card>
      </div>
    </div>
  );
}
