import { useState, useCallback } from 'react';
import type { CommandReport } from '@/hooks/useHeraldCommand';
import { SERVICE_EMOJIS, PRIORITY_COLORS } from '@/lib/herald-types';

interface Props {
  report: CommandReport | null;
}

function CopyBtn({ text, label }: { text: string; label: string }) {
  const [copied, setCopied] = useState(false);
  const copy = useCallback(() => {
    navigator.clipboard.writeText(text);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  }, [text]);

  return (
    <button
      onClick={copy}
      style={{
        fontSize: 18,
        color: '#FFFFFF',
        border: '1px solid #0F1820',
        padding: '4px 10px',
        borderRadius: 2,
        background: 'transparent',
        cursor: 'pointer',
        letterSpacing: '0.05em',
      }}
    >
      {copied ? 'COPIED' : label}
    </button>
  );
}

function SectionTitle({ children }: { children: React.ReactNode }) {
  return (
    <div style={{ fontSize: 18, color: '#FFFFFF', letterSpacing: '0.25em', marginBottom: 8 }}>
      {children}
    </div>
  );
}

function Card({ children, className }: { children: React.ReactNode; className?: string }) {
  return (
    <div
      className={className}
      style={{ border: '1px solid #0F1820', borderRadius: 4, padding: 14 }}
    >
      {children}
    </div>
  );
}

export function ReportDetail({ report }: Props) {
  if (!report) {
    return (
      <div className="flex flex-col items-center justify-center h-full">
        <span className="font-heading" style={{ fontSize: 48, color: '#0D1117' }}>
          HERALD COMMAND
        </span>
        <span style={{ fontSize: 18, color: '#FFFFFF', letterSpacing: '0.2em', marginTop: 8 }}>
          SELECT A TRANSMISSION
        </span>
      </div>
    );
  }

  const a = report.assessment;
  const priority = a?.priority ?? report.priority ?? 'P3';
  const col = PRIORITY_COLORS[priority] ?? '#34C759';
  const service = a?.service ?? report.service ?? 'unknown';
  const emoji = SERVICE_EMOJIS[service] ?? '📻';
  const ts = new Date(report.created_at ?? report.timestamp);
  const timeStr = ts.getUTCHours().toString().padStart(2, '0') + ':' +
    ts.getUTCMinutes().toString().padStart(2, '0') + ':' +
    ts.getUTCSeconds().toString().padStart(2, '0') + 'Z';
  const dateStr = ts.toISOString().slice(0, 10);

  const structured = a?.structured ?? {};
  const actions = a?.actions ?? [];
  const formattedReport = a?.formatted_report ?? '';
  const headline = a?.headline ?? report.headline ?? '';
  const confidence = a?.confidence ?? 0;
  const transmitTo = a?.transmit_to ?? '';
  const protocol = a?.protocol ?? '';
  const priorityLabel = a?.priority_label ?? '';

  // ePRF mapping
  const location = structured['E'] ?? structured['Location'] ?? structured['grid'] ?? 'Not specified';
  const clinicalFindings = Object.entries(structured).map(([k, v]) => `${k}: ${v}`).join('. ');
  const treatmentGiven = actions.join('. ');
  const eprfText = `INCIDENT DATE/TIME: ${dateStr} ${timeStr}
INCIDENT TYPE: ${protocol}
LOCATION: ${location}
CHIEF COMPLAINT: ${headline}
HISTORY: ${report.transcript ?? 'N/A'}
CLINICAL FINDINGS: ${clinicalFindings}
TREATMENT GIVEN: ${treatmentGiven}
PRIORITY: ${priorityLabel}
CREW NOTES: Generated by Herald Radio Intelligence`;

  return (
    <div className="h-full overflow-y-auto p-3 flex flex-col gap-3" style={{ scrollbarWidth: 'thin' }}>
      {/* Priority Banner */}
      <div
        style={{
          background: `${col}1F`,
          borderBottom: `2px solid ${col}`,
          borderRadius: 4,
          padding: '14px 16px',
        }}
      >
        <div className="flex items-start justify-between">
          <div>
            <div className="flex items-center gap-3">
              <span style={{ fontSize: 32 }}>{emoji}</span>
              <span className="font-heading" style={{ fontSize: 38, color: col }}>
                {priority}
              </span>
            </div>
            <div style={{ fontSize: 18, color: `${col}CC`, marginTop: 2 }}>{priorityLabel}</div>
          </div>
          <div className="text-right">
            <div style={{ fontSize: 18, color: '#FFFFFF', textTransform: 'uppercase' }}>{service}</div>
            <div style={{ fontSize: 18, color: '#FFFFFF', marginTop: 2 }}>{timeStr}</div>
          </div>
        </div>
      </div>

      {/* Headline */}
      <Card>
        <p style={{ fontSize: 18, color: '#FFFFFF', lineHeight: 1.6 }}>{headline}</p>
      </Card>

      {/* Two col grid */}
      <div className="grid grid-cols-1 md:grid-cols-2 gap-3">
        {/* Protocol Fields */}
        <Card>
          <SectionTitle>PROTOCOL FIELDS</SectionTitle>
          <div className="flex flex-col gap-2">
            {Object.entries(structured).map(([k, v]) => (
              <div key={k}>
                <div style={{ fontSize: 18, fontWeight: 700, color: '#FFFFFF' }}>{k}</div>
                <div style={{ fontSize: 18, color: '#FFFFFF', lineHeight: 1.4 }}>{v}</div>
              </div>
            ))}
            {Object.keys(structured).length === 0 && (
              <span style={{ fontSize: 18, color: '#FFFFFF' }}>No structured fields</span>
            )}
          </div>
        </Card>

        {/* Actions */}
        <Card>
          <SectionTitle>IMMEDIATE ACTIONS</SectionTitle>
          <div className="flex flex-col gap-1.5">
            {actions.map((act, i) => (
              <div key={i} className="flex gap-2">
                <span style={{ fontSize: 18, fontWeight: 700, color: col }}>{i + 1}.</span>
                <span style={{ fontSize: 18, color: '#FFFFFF' }}>{act}</span>
              </div>
            ))}
          </div>
          {transmitTo && (
            <>
              <div style={{ borderTop: '1px solid #0F1820', margin: '10px 0' }} />
              <div style={{ fontSize: 18, color: '#FFFFFF' }}>TRANSMIT TO: {transmitTo}</div>
            </>
          )}
        </Card>
      </div>

      {/* Formatted Report */}
      <Card>
        <div className="flex items-center justify-between mb-2">
          <SectionTitle>FORMATTED REPORT</SectionTitle>
          <CopyBtn text={formattedReport} label="COPY" />
        </div>
        <pre style={{ fontSize: 18, color: '#FFFFFF', lineHeight: 1.8, whiteSpace: 'pre-wrap' }}>
          {formattedReport || 'No formatted report available'}
        </pre>
      </Card>

      {/* Raw Transmission */}
      <Card>
        <SectionTitle>RAW TRANSMISSION</SectionTitle>
        <p style={{ fontSize: 18, color: '#FFFFFF', fontStyle: 'italic' }}>
          &ldquo;{report.transcript ?? 'N/A'}&rdquo;
        </p>
        <div style={{ fontSize: 18, color: '#FFFFFF', marginTop: 6 }}>
          CONFIDENCE: {Math.round(confidence * 100)}%
        </div>
      </Card>

      {/* ePRF Export */}
      <Card>
        <div className="flex items-center justify-between mb-2">
          <div style={{ fontSize: 18, color: '#3DFF8C', letterSpacing: '0.25em' }}>ePRF READY</div>
          <CopyBtn text={eprfText} label="COPY ePRF" />
        </div>
        <pre style={{ fontSize: 18, color: '#FFFFFF', lineHeight: 1.6, whiteSpace: 'pre-wrap' }}>
          {eprfText}
        </pre>
      </Card>
    </div>
  );
}
